# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('src/gui/icon.ico', 'gui'),
        ('src/gui/themes/video_encoder_dark.json', 'gui/themes'),
    ],
    hiddenimports=[
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.sip',
        'PIL',
        'gui',
        'gui.main_window',
        'gui.styles',
        'gui.workers',
        'gui.tabs',
        'gui.tabs.files_tab',
        'gui.tabs.ffmpeg_tab',
        'gui.tabs.ffmpeg_command_util',
        'gui.tabs.handbrake_tab',
        'gui.tabs.settings_tab',
        'gui.tabs.debug_tab',
        'gui.tabs.about_tab',
        'gui.widgets',
        'gui.widgets.file_list',
        'gui.widgets.log_viewer',
        'gui.widgets.progress_bar',
        'gui.widgets.toast',
        'gui.dialogs.set_tracks_dialog',
        'core',
        'core.encoder',
        'core.ffmpeg_translator',
        'core.file_scanner',
        'core.package_manager',
        'core.preset_parser',
        'core.track_analyzer',
        'utils',
        'utils.config',
        'utils.logger',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ffmpeg_encode',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_window_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='src/gui/icon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='ffmpeg_encode',
)
